Output example.gif
Require npm
Set WindowBar Colorful

type npm run start
sleep 300ms
enter

sleep 3000ms

# create new user
enter
type Danik
enter
type daink@example.com
enter
# confirm creating
sleep 500ms
enter

# print all users
down
enter

# edit email of "Danik"
down 2
enter
enter
down
enter
type danik@example.com
enter

# remove user
down 3
enter
enter
enter

# exit program
down 5
sleep 500ms
enter

# wait until finishing recording
sleep 1000ms