name: vhs
on: workflow_dispatch
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: sudo apt install ffmpeg
      - run: mkdir -p ~/.local/bin/
      - run: wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64 -O ~/.local/bin/ttyd
      - run: wget https://github.com/charmbracelet/vhs/releases/download/v0.8.0/vhs_0.8.0_Linux_x86_64.tar.gz && tar xzf vhs_0.8.0_Linux_x86_64.tar.gz -C .
      - run: mv vhs_0.8.0_Linux_x86_64 ~/.local/bin/vhs
      - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: vhs vhs.tape
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-updater
          commit_user_email: actions@github.com
          commit_author: vhs-updater <actions@github.com>
          file_pattern: '*.gif'
