name: vhs
on: workflow_dispatch
jobs:
  vhs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: sudo apt install ffmpeg
      - run: mkdir -p ~/.local/bin/
      - run: sudo wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64 -O /usr/bin/ttyd
      - run: wget https://github.com/charmbracelet/vhs/releases/download/v0.8.0/vhs_0.8.0_Linux_x86_64.tar.gz && tar xzf vhs_0.8.0_Linux_x86_64.tar.gz
      - run: mv vhs_0.8.0_Linux_x86_64 ~/.local/bin/vhs-0.8
      - run: chmod +x ~/.local/bin/vhs-0.8/vhs && sudo chmod +x /usr/bin/ttyd
      - run: ~/.local/bin/vhs-0.8/vhs vhs.tape
      #- env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
      - run: |
          git config --global user.name 'VHS action'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git commit -am "Updated VHS GIF"
          git push
